AVERAGE_SPEED_MPH = 55.0

MAX_DRIVING_HOURS = 11.0
MAX_DUTY_WINDOW_HOURS = 14.0
DRIVING_BEFORE_BREAK_HOURS = 8.0
REQUIRED_BREAK_HOURS = 0.5
REQUIRED_OFF_DUTY_HOURS = 10.0

CYCLE_LIMIT_HOURS = 70.0
CYCLE_DAYS = 8
RESTART_HOURS = 34.0

PICKUP_HOURS = 1.0
DROPOFF_HOURS = 1.0
FUEL_INTERVAL_MILES = 1000.0
FUEL_STOP_HOURS = 0.5

STATUS_OFF_DUTY = "off_duty"
STATUS_SLEEPER = "sleeper_berth"
STATUS_DRIVING = "driving"
STATUS_ON_DUTY = "on_duty"

SECONDS_PER_DAY = 24 * 3600
